s = """gaggtaaagcttcaggagtc-gaggtacagcttcaggagtc-gaggtgaagcttcaggagtc-gaggtgcagcttcaggagtc-gatgtaaagcttcaggagtc-gatgtacagcttcaggagtc-gatgtgaagcttcaggagtc-gatgtgcagcttcaggagtc-
gaggtccagctccagcagtc-gaggtccagctgcagcagtc-gaggtccagcttcagcagtc-gaggtgcagctccagcagtc-gaggtgcagctgcagcagtc-gaggtgcagcttcagcagtc-gaggttcagctccagcagtc-gaggttcagctgcagcagtc-gaggttcagcttcagcagtc-
caggtgcagctgaaggagtc-caggtgcagctgaaggactc-caggtgcagctgaagcagtc-caggtgcagctgaagcactc-
gaggtccaactgcaacaatc-gaggtccaactgcaacagtc-gaggtccagctgcaacaatc-gaggtccagctgcaacagtc-
caggtccagctccagcaatc-caggtccagctccagcagtc-caggtccagctgcagcaatc-caggtccagctgcagcagtc-caggtccagcttcagcaatc-caggtccagcttcagcagtc-caggttcagctccagcaatc-caggttcagctccagcagtc-caggttcagctgcagcaatc-caggttcagctgcagcagtc-caggttcagcttcagcaatc-caggttcagcttcagcagtc-
caggtccaactgcagcagtc-caggtccagctgcagcagtc-caggttcaactgcagcagtc-caggttcagctgcagcagtc-
caggtccacgtgaagcagtc-
gaggtgaaggtggtggaatc-gaggtgaagctggtggaatc-gaggtgaacgtggtggaatc-gaggtgaacctggtggaatc-
gaagtgaagctggtggagtc-gaagtgaagttggtggagtc-gaagtgatgctggtggagtc-gaagtgatgttggtggagtc-gacgtgaagctggtggagtc-gacgtgaagttggtggagtc-gacgtgatgctggtggagtc-gacgtgatgttggtggagtc-gaggtgaagctggtggagtc-gaggtgaagttggtggagtc-gaggtgatgctggtggagtc-gaggtgatgttggtggagtc-
gaggtgcagggggtggagtc-gaggtgcaggtggtggagtc-gaggtgcagcgggtggagtc-gaggtgcagctggtggagtc-
gaggtgcaactggtggagtc-gaggtgcacctggtggagtc-gatgtgcaactggtggagtc-gatgtgcacctggtggagtc-
gaggtgaagctgatggaatc-gaggtgaagctgatggagtc-
gaggtgcaacttgttgagtc-gaggtgcagcttgttgagtc-
gaagtaaagcttctcgagtc-gaagtgaagcttctcgagtc-gaggtaaagcttctcgagtc-gaggtgaagcttctcgagtc-
gaagtgaaagttgaggagtc-gaagtgaaacttgaggagtc-gaagtgaaggttgaggagtc-gaagtgaagcttgaggagtc-
caggttactctaaaagagtgtg-caggttactctaaaagagtctg-caggttactctaaaagtgtgtg-caggttactctaaaagtgtctg-caggttactctgaaagagtgtg-caggttactctgaaagagtctg-caggttactctgaaagtgtgtg-caggttactctgaaagtgtctg-
caggtccaactacagcaacc-caggtccaactacagcagcc-caggtccaactccagcaacc-caggtccaactccagcagcc-caggtccaactgcagcaacc-caggtccaactgcagcagcc-
gatgtgaacttggaagtgtc-
gaggtgaaggtcatcgagtc-"""

print(s.replace('-', '\n'))



